### ISSUE TITLE
Extra comma that newer versions of Terser don't like

### ISSUE THREAD

**Issue by daveisfera** [exlexer/classNameMaker#2]
I was playing around with web pack 5, and when turning on minify, Terser complains about this comma because it expects the code to be standard compliant (i.e. we currently don't run our `node_modules` through `babel`):
https://github.com/exlexer/classNameMaker/blob/6f36dde6dcbe80a470c38414aaae515f5ddccb12/classnamemaker.js#L25d

**Comment by exlexer** [comment]
This comma was removed in c781c7713318d11dec37e82a9914b184a0c0b520
